services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "/var/lib/postgresql/data"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  MQ:
    image: rabbitmq:3
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS="./firebase-adminsdk.json"
    depends_on:
      - database
      - redis
      - MQ
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/campus-fora-backend
    privileged: true
volumes:
  data:
